### ISSUE TITLE
Error on applying format using Format Painter

### ISSUE THREAD

**Issue by HansinVogado** [archimatetool/archi#1075]
### Archi Version

5.4.0

### Operating System

Windows 10

### Description

Format Painter does not work properly. Not all format is applied when element has image.

!ENTRY org.eclipse.ui 4 0 2024-09-10 16:19:57.984
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException: Cannot invoke "com.archimatetool.editor.model.IArchiveManager.getBytesFromEntry(String)" because "archiveManager" is null
	at com.archimatetool.editor.model.impl.ArchiveManager.copyImageBytes(ArchiveManager.java:286)
	at com.archimatetool.editor.diagram.tools.FormatPainterTool.createCommand(FormatPainterTool.java:283)
	at com.archimatetool.editor.diagram.tools.FormatPainterTool.handleButtonUp(FormatPainterTool.java:81)
	at org.eclipse.gef.tools.AbstractTool.mouseUp(AbstractTool.java:1215)
	at org.eclipse.gef.EditDomain.mouseUp(EditDomain.java:303)
	at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMouseReleased(DomainEventDispatcher.java:408)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseUp(LightweightSystem.java:586)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:237)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4083)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at com.archimatetool.editor.Application.start(Application.java:85)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)

**Comment by Phillipus** [comment]
Please could you provide the steps to reproduce this and possibly a simple test model to reproduce.

**Comment by Phillipus** [comment]
Never mind, I can reproduce this.

**Comment by Phillipus** [comment]
This is a bug if the source object contains an image. I'll get a fix out tomorrow.

**Comment by Phillipus** [comment]
This is fixed in Archi 5.4.1 available now. Thanks for reporting!
