### ISSUE TITLE
Arch4 Beta crash on launch

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#159]
Running Windows 10 Pro 64bit version 1511 on a Lenovo E540 i7-4712MQ 2.3 GHz with 8 GB RAM

Error log contents:

!SESSION 2016-11-03 12:36:46.437 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=en_ZA
Command-line arguments:  -os win32 -ws win32 -arch x86 -clean

!ENTRY org.eclipse.osgi 2 0 2016-11-03 12:36:48.000
!MESSAGE com.archimatetool.editor.Application cannot be found by com.archimatetool.editor_4.0.0.201611021627
!STACK 0
java.lang.ClassNotFoundException: com.archimatetool.editor.Application cannot be found by com.archimatetool.editor_4.0.0.201611021627
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:564)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:191)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

!ENTRY com.archimatetool.editor.fullscreen.macos 2 0 2016-11-03 12:36:48.000
!MESSAGE Could not resolve module: com.archimatetool.editor.fullscreen.macos [8]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.ws=cocoa)"

!ENTRY org.eclipse.osgi 4 0 2016-11-03 12:36:48.000
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in com.archimatetool.editor was unable to load class com.archimatetool.editor.Application.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:191)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.ClassNotFoundException: com.archimatetool.editor.Application cannot be found by com.archimatetool.editor_4.0.0.201611021627
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:564)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	... 15 more

**Comment by Phillipus** [comment]
Hi,

I can't reproduce this on my 64-bit Windows machine. Could you try:
- Download again
- Unzip again
- Different machine

Any more info?

**Comment by theunsfvo** [comment]
Hi Phillipus,

Tried it again and extracted it in the download folder and ran it from there and it worked...

One thing I did do before which I probably shouldn't have, was to rename the folder from Archi to Archi4.

Anyways, got the beta to run, will begin testing it...

**Comment by theunsfvo** [comment]
Thanks :)

**Comment by Phillipus** [comment]
Good to hear. Renaming the folder shouldn't cause this.

**Comment by theunsfvo** [comment]
I did it INSIDE the zip before extracting to my Program Files (x86)
folder... perhaps its a Windows permission issue in this folder?

​Don't know... will try moving the extracted folder to there and test​...

Thanks Phil...

Regards,
Theuns

**Comment by Phillipus** [comment]
Yes, I think if you unzip to Program Files (x86) it could be a permissions issue. You'd need to do it as Administrator I think.

**Comment by Phillipus** [comment]
Yes, I think if you unzip to Program Files (x86) it could be a permissions issue. You'd need to do it as Administrator I think.

**Comment by Phillipus** [comment]
Yes, I think if you unzip to Program Files (x86) it could be a permissions issue. You'd need to do it as Administrator I think.

**Comment by Phillipus** [comment]
Yes, I think if you unzip to Program Files (x86) it could be a permissions issue. You'd need to do it as Administrator I think.

**Comment by Phillipus** [comment]
Yes, I think if you unzip to Program Files (x86) it could be a permissions issue. You'd need to do it as Administrator I think.
