### ISSUE TITLE
[Bug] Association with a relationship cause an error and Visualizer does show up an other relations

### ISSUE THREAD

**Issue by szuniga** [archimatetool/archi#428]
!ENTRY org.eclipse.ui.workbench 4 2 2019-01-10 13:34:19.439
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.ClassCastException: com.archimatetool.model.impl.AssignmentRelationship cannot be cast to com.archimatetool.model.IArchimateElement
	at com.archimatetool.zest.ZestViewerContentProvider.getRelations(ZestViewerContentProvider.java:142)
	at com.archimatetool.zest.ZestViewerContentProvider.getRelations(ZestViewerContentProvider.java:150)
	at com.archimatetool.zest.ZestViewerContentProvider.getElements(ZestViewerContentProvider.java:109)
	at org.eclipse.zest.core.viewers.internal.GraphModelFactory.doBuildGraph(GraphModelFactory.java:54)
	at org.eclipse.zest.core.viewers.internal.GraphModelFactory.createGraphModel(GraphModelFactory.java:42)
	at org.eclipse.zest.core.viewers.internal.AbstractStructuredGraphViewer.inputChanged(AbstractStructuredGraphViewer.java:481)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:286)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1685)
	at com.archimatetool.zest.DrillDownManager.setGraphViewerInput(DrillDownManager.java:75)
	at com.archimatetool.zest.DrillDownManager.setNewInput(DrillDownManager.java:66)
	at com.archimatetool.zest.ZestView.setElement(ZestView.java:202)
	at com.archimatetool.zest.ZestView.selectionChanged(ZestView.java:183)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:239)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:172)
	at org.eclipse.ui.internal.WorkbenchWindow$WWinPartService.partActivated(WorkbenchWindow.java:3011)
	at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4990)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4987)
	at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4975)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:212)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:247)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:756)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:681)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:676)
	at org.eclipse.ui.internal.WorkbenchPage.activate(WorkbenchPage.java:993)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3222)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3176)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3158)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3153)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3117)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3107)
	at com.archimatetool.editor.ui.services.EditorManager.openEditor(EditorManager.java:54)
	at com.archimatetool.editor.ui.services.EditorManager.openDiagramEditor(EditorManager.java:114)
	at com.archimatetool.editor.ui.services.EditorManager.openDiagramEditor(EditorManager.java:79)
	at com.archimatetool.editor.views.tree.TreeModelView.handleOpenAction(TreeModelView.java:223)
	at com.archimatetool.editor.views.tree.TreeModelView.access$1(TreeModelView.java:207)
	at com.archimatetool.editor.views.tree.TreeModelView$1.doubleClick(TreeModelView.java:147)
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:831)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:828)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1459)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1258)
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:249)
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:247)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:306)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.archimatetool.editor.Application.start(Application.java:82)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

### Version of Archi, Operating System

Windows
### Expected Behaviour

On associating an application component with an assigmnent relationship we expected to be able to visualize this association relationship
### Actual Behaviour

The association relationship between the application component and an assignment relationship is not shown on the visualizer and sometimes even give an error.
### Steps to Reproduce the Behaviour
1. Assign a bussiness actor to a role.
2. Associate an application component to the assignment relationship between the business actor and the role
3. Try to visualize this relationship.

**Comment by Phillipus** [comment]
Thanks, I can reproduce this. Working on a fix...

**Comment by Phillipus** [comment]
...fixed. I'll get a new build out in the coming days.

**Comment by Phillipus** [comment]
Fixed in Archi 4.3.2. Please re-open if the issue re-occurs.
