### ISSUE TITLE
[Bug] java.lang.NullPointerException thrown when loading a model

### ISSUE THREAD

**Issue by VladislavEkimtcov** [archimatetool/archi#461]
Hello! I've been using Archi pretty extensively, and even decided to set up a machine to automate some Archi activities. However, I do have this problem:

### Version of Archi, Operating System

Archi version: 4.3.3 32 bit
I am on xubuntu that self-identifies as Ubuntu 16.04.2 LTS, codename xenial.
The one and only Java machine installed is openjdk 1.8.0_191.

### Expected Behaviour

I am trying to load the model and dump it into HTML with the following command:
`./Archi -application com.archimatetool.commandline.app -consoleLog --modelrepository.loadModel a.archimate --html.createReport /home/archi/ArchiDump/ `

Note: a.archimate is a model with one single element created in the same Archi copy that I'm having issues with.

### Actual Behaviour

Judging from the output, it starts to load the model, but throws an exception:
`[LoadModelFromRepositoryProvider] Loading model at a.archimate
java.lang.NullPointerException
	at com.archimatetool.editor.model.impl.ArchiveManager.<init>(ArchiveManager.java:107)
	at com.archimatetool.editor.model.IArchiveManager$FACTORY.createArchiveManager(IArchiveManager.java:35)
	at org.archicontribs.modelrepository.commandline.LoadModelFromRepositoryProvider.loadModel(LoadModelFromRepositoryProvider.java:146)
	at org.archicontribs.modelrepository.commandline.LoadModelFromRepositoryProvider.run(LoadModelFromRepositoryProvider.java:133)
	at com.archimatetool.commandline.CentralScrutinizer.runProviderOptions(CentralScrutinizer.java:159)
	at com.archimatetool.commandline.CentralScrutinizer.start(CentralScrutinizer.java:80)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
java.io.IOException: Model was not loaded
	at com.archimatetool.reports.commandline.HTMLReportProvider.run(HTMLReportProvider.java:65)
	at com.archimatetool.commandline.CentralScrutinizer.runProviderOptions(CentralScrutinizer.java:159)
	at com.archimatetool.commandline.CentralScrutinizer.start(CentralScrutinizer.java:80)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)`

### Steps to Reproduce the Behaviour
1. Install 32 bit Archi 4.3.3 on Xubuntu LTS and openjdk 8 as specified above
2. Run the command in terminal on any model

**Comment by jbsarrodie** [comment]
>I am trying to load the model and dump it into HTML with the following command:
>`./Archi -application com.archimatetool.commandline.app -consoleLog --modelrepository.loadModel a.archimate --html.createReport /home/archi/ArchiDump/`

You are using the wrong argument to load the model: You should use `--loadModel` instead of `--modelrepository.loadModel` (which is only useful when using the Collaboration plugin).

Check https://github.com/archimatetool/archi/wiki/Archi-Command-Line-Interface for all supported arguments.

Regards

**Comment by Phillipus** [comment]
Yes, please use `--loadModel` instead of `--modelrepository.loadModel`

I've put a check for null in that part of the code now. It will throw an exception instead.
