### ISSUE TITLE
[jArchi] Feature request: support attribute .labelExpression for relations

### ISSUE THREAD

**Issue by rchevallier** [archimatetool/archi#903]
### Version of Archi
Archi v4.10.0

### Archi Plug-ins
jArchi v1.3.1

### Operating System
Windows 10

### Feature request
Support the attribute .labelExpression in jArchi for relation, the same way it is accessible an attribute in jArchi for an element

### Actual status
Trying to use the 
GraalVM error: 
javax.script.ScriptException: com.archimatetool.script.ArchiScriptException: Label expressions are not supported for association-relationship: resp of
	at com.archimatetool.script.dom.model.EObjectProxy.setLabelExpression(EObjectProxy.java:460)
	at <js>.:=>(Apply specialization label.ajs:101)
	at com.oracle.truffle.polyglot.PolyglotFunctionProxyHandler.invoke(PolyglotFunctionProxyHandler.java:155)
	at com.sun.proxy.$Proxy38.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)

**Comment by Phillipus** [comment]
Hi, label expressions are already in place for diagram connections:

```
var selected = selection.first(); // selected must be a diagram connection not a model relationship
selected.labelExpression="Hello"
```
