### ISSUE TITLE
"create report from command line" problem with different domain user 

### ISSUE THREAD

**Issue by oozpostaci** [archimatetool/archi#988]
Hi,
I can run the following command with my user on windows succesfully . But I can't run this command with another domain user. Model wad not loaded error appears.  Can you help me ? 

Archi -application com.archimatetool.commandline.app -consoleLog -nosplash  --modelrepository.loadModel c:\archimodels\model1698317910840 --html.createReport   c:\archi4 -p

### Version of Archi
5.0.1
### Archi Plug-ins
jarchi
### Operating System
windows

### Expected Behaviour
create HTML report gtom command line

### Actual Behaviour
java.io.IOException: Model was not loaded
        at com.archimatetool.reports.commandline.HTMLReportProvider.run(HTMLReportProvider.java:66)
        at com.archimatetool.commandline.CentralScrutinizer.runProviderOptions(CentralScrutinizer.java:164)
        at com.archimatetool.commandline.CentralScrutinizer.start(CentralScrutinizer.java:82)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
`--modelrepository.loadModel` requires the path to a model file such as `model.archimate`. Your path looks like a directory.

**Comment by oozpostaci** [comment]
hi, this directory contains model files that cloned from git.  its subfolders are applications, business , diagrams ....

**Comment by Phillipus** [comment]
> hi, this directory contains model files that cloned from git. its subfolders are applications, business , diagrams ....

In this case you use `--modelrepository.loadModel <folder>`

**Comment by Phillipus** [comment]
Sorry, I'm getting confused here. You are using the correct parameter.

**Comment by oozpostaci** [comment]
yes , user has permissions

**Comment by oozpostaci** [comment]
Thank you Phillipus. I will search HTMLReportProvide class. Maybe I can find solution .

**Comment by oozpostaci** [comment]
..

**Comment by Phillipus** [comment]
Hi, all you need to do is answer this question:

Do you see the following in the console?

```
[LoadModelFromRepositoryProvider] Loading model at c:\archimodels\model1698317910840
[LoadModelFromRepositoryProvider] Loaded model: 'Model Name'
```

**Comment by oozpostaci** [comment]
No . I dont see. But I realized that if I use --loadModel parameter with archimate file this user create HTML reports. I think , this user has not got some policies in my company. This is problem .

**Comment by Phillipus** [comment]
If `--modelrepository.loadModel` fails for some reason the model will not be loaded and then this will cause the HTML report to fail.
